### ISSUE TITLE
It doesn't show the newest tag.

### ISSUE THREAD

**Issue by Vatanay** [tremby/laravel-git-version#10]
I downloaded the package. Although there are dozens of release tags on my Github (Laravel project), it showed one of the old ones.

<img width="81" alt="image" src="https://user-images.githubusercontent.com/51656705/157606481-b8bb65c9-8ba1-4db0-9b29-b4e3ffc060c1.png">

However, we are on version 1.5.4

**Comment by tremby** [comment]
The package doesn't know what tags you have on Github, nor does it attempt to find out. It only knows what's on the machine where `git describe` is run. Do the tags exist there? Have they been fetched from wherever they exist (Github in this case)? Run `git tag` in a shell to find out what tags you have. You can fetch tags from your remote with `git fetch --tags`.

**Comment by Vatanay** [comment]
I used exec('git describe --tags') . It is working correctly for now. Thanks a lot for your quick reply.
