### ISSUE TITLE
Detected dubious ownership in repository

### ISSUE THREAD

**Issue by ashokdevatwal** [tremby/laravel-git-version#11]
The command  git describe --always --tags --dirty  failed.

Exit Code: 128(Invalid exit argument)

Working directory: /var/www/abc/project

Error Output:
================
fatal: detected dubious ownership in repository at  /var/www/abc/project 
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www/abc/project

**Comment by tremby** [comment]
That's nothing to do with this package.

Git has decided something is not right with file ownership within your repository; do web searches for the error message to find out more, and how to fix it.
