### ISSUE TITLE
Does not work with symfony/process < v4.0

### ISSUE THREAD

**Issue by ngugijames** [tremby/laravel-git-version#8]
Installing on a Laravel 5.5 project with "symfony/process": "v3.4.39", fails with the following error:

In GitVersionHelper.php line 43:
                                                                               
  Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() 

It seems the function fromShellCommandline was added in  symfony/process: v4.0

To support older versions of process, a better approach would be:

    if (method_exists(Process::class, 'fromShellCommandline')) {
            $process = Process::fromShellCommandline($command);
        } else {
            $process = new Process($command);
        }
}

I will submit a PR later.

**Comment by tremby** [comment]
The suggested packages part of composer.json https://github.com/tremby/laravel-git-version/blob/master/composer.json#L8 does mention that version 4+ is expected, but I'll accept the PR once complete.

Didn't realize an in-support version of Laravel (5.5) still used a version so old.

**Comment by ngugijames** [comment]
Laravel 5.5 only symfony/process: ~3.3 as seen here https://github.com/laravel/framework/blob/5.5/composer.json#L36

**Comment by tremby** [comment]
Indeed

**Comment by tremby** [comment]
Fixed in 52e423040f3615d5ccd21a45afcbaf4f52661be2; thanks.
